mysite/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='home'),  # maps to the index view for the home path
    path('home/', views.index, name='home'),
    path('movies/', views.movies, name='movies'),
    path('transaction/', views.transaction_view, name='transaction'),
    path('contactus/', views.contact_us, name='contact_us'),
    path('aboutus/', views.about_us, name='about_us'),
    #path('movie_details/<str:movie_type>/<int:movie_id>/', views.movie_details, name='movie_details'),


]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main import views  # Assuming your views are in the 'main' app

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name='home'),  # Fixed the view reference
    path('', include("main.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/main/models.py
from django.db import models

# Create your models here.

class NowShowingMovie(models.Model):
    name = models.CharField(max_length=50)
    image = models.URLField(default='https://user-images.githubusercontent.com/52632898/161646398-6d49eca9-267f-4eab-a5a7-6ba6069d21df.png')
    date = models.DateField()
    duration = models.CharField(max_length=50)
    type = models.CharField(max_length=50)
    showtime = models.CharField(max_length=50)
    rating = models.CharField(max_length=50)
    cast = models.TextField(max_length=100)
    trailer = models.CharField(max_length=100)
    up = models.BooleanField(default=False)
    id = models.BigAutoField(primary_key=True)

# Define a model for upcoming movies
class UpcomingMovie(models.Model):
    name = models.CharField(max_length=50)
    image = models.URLField(default='https://user-images.githubusercontent.com/52632898/161646398-6d49eca9-267f-4eab-a5a7-6ba6069d21df.png')
    date = models.DateField()
    duration = models.CharField(max_length=50)
    type = models.CharField(max_length=50)
    showtime = models.CharField(max_length=50)
    rating = models.CharField(max_length=50)
    cast = models.TextField(max_length=100)
    trailer = models.CharField(max_length=100)
    release_date = models.DateField()
    id = models.BigAutoField(primary_key=True)

class Reg(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=100)
    mobile = models.IntegerField()
    age = models.IntegerField()
    seats = models.IntegerField()
    id = models.BigAutoField(primary_key=True)

# Define a model for user contacts
class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    id = models.BigAutoField(primary_key=True)

    def __str__(self):
        return self.name

# Define a model for transactionsx
class Transaction(models.Model):
    date = models.DateField()
    movie = models.ForeignKey(NowShowingMovie, on_delete=models.CASCADE)
    show_time = models.CharField(max_length=50)
    user_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=15)
    seat_number = models.CharField(max_length=10)
    card_number = models.CharField(max_length=16)
    expiry_date = models.DateField()
    cvv = models.CharField(max_length=3)
    card_holder_name = models.CharField(max_length=100)
    id = models.BigAutoField(primary_key=True)

    def __str__(self):
        return f"{self.user_name} - {self.movie.name} - {self.date}"

mysite/main/forms.py
from django import forms
from .models import Reg, Contact

class RegForm(forms.ModelForm):
    class Meta:
        model = Reg
        fields = "__all__"

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = "__all__"

mysite/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import NowShowingMovie, UpcomingMovie, Contact, Transaction, Reg
from main.forms import RegForm, ContactForm 


# Create your views here.
def index(request):
    #return HttpResponse("Thi is home page!")
    now_showing_movies = NowShowingMovie.objects.all()
    upcoming_movies = UpcomingMovie.objects.all()
    return render(request, 'main/index.html', {'now_showing_movies': now_showing_movies, 'upcoming_movies': upcoming_movies})

def movies(request):
    #return HttpResponse("Thi is movies page!")
    now_showing_movies = NowShowingMovie.objects.all()
    upcoming_movies = UpcomingMovie.objects.all()
    return render(request, 'main/movies.html', {'now_showing_movies': now_showing_movies, 'upcoming_movies': upcoming_movies})


#def movie_details(request, movie_type, movie_id):
    model_class = None
    template_name = 'movie_details.html'

    if movie_type == 'now_showing':
        model_class = NowShowingMovie
    elif movie_type == 'upcoming':
        model_class = UpcomingMovie
    else:
        # Handle invalid movie_type, maybe raise a 404 or redirect
        pass

    movie = get_object_or_404(model_class, pk=movie_id)
    return render(request, template_name, {'movie': movie, 'movie_type': movie_type})


def transaction(request, movie_id):
    # Implement your transaction logic
    # For example, create a new transaction record and redirect to a payment page
    return render(request, 'main/transaction.html', {'movie_id': movie_id})


#def login(request):
    return render(request, 'loginform.html')

#def signup(request):
    if request.method == "POST":
        form = RegForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/booked")
    else:
        form = RegForm()
    return render(request, 'signup.html', {'form': form})

#def booked(request):
    booked_customers = Reg.objects.all()
    return render(request, 'booked.html', {'booked_customers': booked_customers})

#def about(request):
    return render(request, 'Untitled-1.html')

#def details(request, id):
    movie_details = NowShowingMovie.objects.get(id=id)
    return render(request, 'details.html', {'movie_details': movie_details})

#def updetails(request, id):
    movie_details = UpcomingMovie.objects.get(id=id)
    return render(request, 'updetails.html', {'movie_details': movie_details})

#def aboutmore(request):
    return render(request, 'about.html')

def contact_us(request):
    #return HttpResponse("Thi is contact us page!")
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse("Thanks for your message! We'll get back to you soon.")
    else:
        form = ContactForm()
    return render(request, 'main/contact.html', {'form': form})

# movie_reservation/views.py
def transaction_view(request):
    #return HttpResponse("Thi is transaction page!")   
    if request.method == 'POST':
        # Process the transaction and save the details in the Transaction model
        # In a real-world scenario, you would handle payment processing and store relevant information in the database.
        # For simplicity, we are just creating a dummy transaction with seat details.
        seat_details = request.POST.getlist('selected_seats[]')
        transaction = Transaction.objects.create(seats=", ".join(seat_details))
        transaction.save()

        return HttpResponse(f'Transaction successful! Transaction ID: {transaction.id}')

    return render(request, 'main/transaction.html')  # Assuming you have a transaction.html template


#def buy_ticket(request):
    if request.method == 'POST':
        # Handle the ticket buying process
        # You can access the form data using request.POST.get('<field_name>')
        # Example: name = request.POST.get('name')
        # Add your ticket buying logic here
        return HttpResponse("Ticket bought successfully!")
    else:
        # Render the buy ticket form
        return render(request, 'buy_ticket.html')


def about_us(request):
    return render(request, 'main/about.html')

mysite/main/templates/main/about.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Home - FILMAX CINEMAS</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha384-aKs2ZL2FZuMKSFi+exvF4jsvTC+4VIxDtvZxMtVVZZzB1MdAzLl3WSdUfKDS3orS" crossorigin="anonymous">

    <style>
          body {
              background-color: black;
              color: #fff;
          }
          .header{
            width: 100%;
           height: 80vh;
           background:url(https://media.istockphoto.com/id/1160221860/video/moving-through-the-dark-modern-cinema-hall-over-the-chairs-to-the-lighting-up-screen.jpg?s=640x640&k=20&c=nGFJlzVIq1PPeS3cD6bcgo2AnLQ6bWOmD_1-HcDgPHc=) no-repeat center center/cover;
           background-attachment: fixed;
           }

           .logo {
            width: 150px; /* Adjust the width as needed */
            height: auto; /* To maintain the aspect ratio */
        }


        .menu-bar {
            font-size: 20px; /* Adjust the font size as needed */
        }


        .nav-link {
            color: white;
            text-decoration: none;
            font-weight: normal; /* Set initial font weight */
            transition: font-weight 0.3s ease; /* Add smooth transition effect */
        }
    
        .nav-link.active,
        .nav-link:hover {
            font-weight: bold; /* Set font weight on hover or when the link is active */
        }



          .site-footer
          {
            background-color:#26272b;
            padding:20px  10px;
            font-size:15px;
            line-height:24px;
            color:#737373;
          }


          .card-title a {
            text-decoration: none; /* Remove underline for movie name */
            font-weight: bold; /* Make movie name text bold */
            color: #fff; /* Set text color to white */
        }

        .card {
            background-color: #d3d3d3; /* Change background color to light gray */
            height: 250px; /* Adjust the height as needed */
        }

        .card-body {
            background-color: #1c1c1c; /* Change background color to light gray */
            
        }

        .movie-image {
            width: 100%;
            height: 0;
            padding-bottom: 5%; /* Set the aspect ratio (height/width * 100) */
            object-fit: cover;
        }

        .card-body img {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }

        .text-center.text-white {
            margin: 40px 0; /* Adjust the values as needed */
            
        }
        .footer-links a {
            color: #737373;
            text-decoration: none; /* Remove the underline */
        }
        
        .footer-links a:hover {
            text-decoration: underline; /* Add underline on hover if needed */
        }
        .section {
          margin-bottom: 60px; /* Adjust the margin as needed */
      }
      
      .centered-title {
        margin-top: 50px; /* Adjust the value as needed */
    }
    

      </style>


</head>

<body>
    <section class="header">
        <div class="container h-100 pt-4 d-flex flex-column justify-content-between">
            <div class="navbar w-100 d-flex flex-row justify-content-between align-items-center">
                <img src="{% static "images/logo.png" %}" width="80" height="100" alt="logo" class="logo">
                <div class="menu-bar d-flex flex-row justify-content-center align-items-center">
                    <a href="{% url 'main:home' %}" class="nav-link active text-white mx-3">Home</a>
                    <a href="{% url 'main:movies' %}" class="nav-link text-white mx-3">Movies</a>
                    <a href="{% url 'main:contact_us' %}" class="nav-link text-white mx-3">Contact Us</a>
                    <a href="{% url 'main:about_us' %}" class="nav-link text-white mx-3">About Us</a>
                </div>
            </div>
            <div class="d-flex flex-column justify-content-center align-items-left mb-5">
                <h1 class="text-white film-name">FILMAX CINEMAS</h1>
            </div>
        </div>
    </section>

    <section class="about-section">
        <div class="container">
            <h1 class="centered-title text-center">About Us</h1>
            <div class="about-content">
                <div class="text-content">
                  <div class="section">
                    <h2>Who We Are</h2>
                    <p>Welcome to Movie Ticket Booking, your go-to platform for a seamless movie-watching experience.
                        Our mission is to provide movie enthusiasts with a convenient and enjoyable way to book tickets
                        online.</p>
                </div>
                
                <div class="section">
                    <h2>Our Vision</h2>
                    <p>We envision a world where everyone can easily access and enjoy their favorite movies at their
                        preferred cinemas. With our user-friendly platform, we aim to simplify the movie ticket booking
                        process.</p>
                </div>
                
                <div class="section">
                    <h2>Why Choose Us?</h2>
                    <ul>
                        <li>Easy and Secure Booking Process</li>
                        <li>Wide Range of Cinemas and Movies</li>
                        <li>Real-time Seat Availability</li>
                        <li>Exclusive Deals and Discounts</li>
                        <li>User-Friendly Interface</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
  

    <footer class="site-footer">
      <div class="container">
          <div class="row">
              <div class="col-sm-12 col-md-6">
                  <h6>About</h6>
                  <p class="text-justify">"Discover the magic of movies with Filmax Cinemas – your go-to destination for an extraordinary cinematic experience. Streamlining convenience and excellence, our cutting-edge app puts showtimes, seat selection, and ticket booking in the palm of your hand. Join us in redefining movie-watching, where innovation meets comfort. Welcome to Filmax Cinemas – where movies come to life!"</p>
              </div>

              <div class="col-md-3">
                  <h6>Quick Links</h6>
                  <ul class="footer-links">
                      <li><a href="{% url 'main:about_us' %}">About Us</a></li>
                      <li><a href="{% url 'main:contact_us' %}">Contact Us</a></li>
                  </ul>
              </div>

              <div class="col-md-3">
                  <h6>Subscribe for Latest Updates</h6>
                  <form action="#" method="post" class="input-group">
                      <input type="email" class="form-control" placeholder="Enter your email">
                      <button class="btn btn-secondary" type="submit">Subscribe</button>
                  </form>
              </div>
          </div>
          <hr>
      </div>
      <div class="container">
          <div class="row">
              <div class="col-md-8 col-sm-6 col-xs-12">
                  <p class="copyright-text">Copyright &copy; 2023 All Rights Reserved by
                      <a href="#" target="_blank">FILMAX CINEMAS</a>.
                  </p>
              </div>
          </div>
      </div>
  </footer>
</body>

</html>

mysite/main/templates/main/movie_details.html
<h1>Movie Details<h1>

mysite/main/templates/main/movies.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home - FILMAX CINEMAS</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha384-aKs2ZL2FZuMKSFi+exvF4jsvTC+4VIxDtvZxMtVVZZzB1MdAzLl3WSdUfKDS3orS" crossorigin="anonymous">

    <style>
          body {
              background-color: black;
              color: #fff;
          }
          .header{
            width: 100%;
           height: 80vh;
           background:url(https://media.istockphoto.com/id/1160221860/video/moving-through-the-dark-modern-cinema-hall-over-the-chairs-to-the-lighting-up-screen.jpg?s=640x640&k=20&c=nGFJlzVIq1PPeS3cD6bcgo2AnLQ6bWOmD_1-HcDgPHc=) no-repeat center center/cover;
           background-attachment: fixed;
           }

           .logo {
            width: 150px; /* Adjust the width as needed */
            height: auto; /* To maintain the aspect ratio */
        }


        .menu-bar {
            font-size: 20px; /* Adjust the font size as needed */
        }


        .menu-bar .nav-link {
            margin-right: 20px; /* Adjust the margin as needed */
        }



          .site-footer
          {
            background-color:#26272b;
            padding:20px  10px;
            font-size:15px;
            line-height:24px;
            color:#737373;
          }

          .card-title a {
            text-decoration: none; /* Remove underline for movie name */
            font-weight: bold; /* Make movie name text bold */
            color: #fff; /* Set text color to white */
        }

        .card {
            background-color: #d3d3d3; /* Change background color to light gray */
            height: 250px; /* Adjust the height as needed */
        }

        .card-body {
            background-color: #1c1c1c; /* Change background color to light gray */
            
        }

        .movie-image {
            width: 100%;
            height: 0;
            padding-bottom: 5%; /* Set the aspect ratio (height/width * 100) */
            object-fit: cover;
        }
        .card-text {
            color: white;
        }
        

        .card-body img {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }
        .text-center.text-white {
            margin: 40px 0; /* Adjust the values as needed */
        }

        .footer-links a {
            color: #737373;
            text-decoration: none; /* Remove the underline */
        }
        
        .footer-links a:hover {
            text-decoration: underline; /* Add underline on hover if needed */
        }

        .nav-link {
            color: white;
            text-decoration: none;
            font-weight: normal; /* Set initial font weight */
            transition: font-weight 0.3s ease; /* Add smooth transition effect */
        }
    
        .nav-link.active,
        .nav-link:hover {
            font-weight: bold; /* Set font weight on hover or when the link is active */
        }

      </style>

</head>

<body>
    <section class="header">
        <div class="container h-100 pt-4 d-flex flex-column justify-content-between">
            <div class="navbar w-100 d-flex flex-row justify-content-between align-items-center">
                 <img src="{% static "images/logo.png" %}" width="80" height="100" alt="logo" class="logo">
                <div class="menu-bar d-flex flex-row justify-content-center align-items-center">
                    <a href="{% url 'main:home' %}" class="nav-link active text-white mx-3">Home</a>
                    <a href="{% url 'main:movies' %}" class="nav-link text-white mx-3">Movies</a>
                    <a href="{% url 'main:contact_us' %}" class="nav-link text-white mx-3">Contact Us</a>
                    <a href="{% url 'main:about_us' %}" class="nav-link text-white mx-3">About Us</a>
                </div>
            </div>
            <div class="d-flex flex-column justify-content-center align-items-left mb-5">
                <h1 class="text-white film-name">FILMAX CINEMAS</h1>
            </div>
        </div>
    </section>

    <section class="screening container mt-5">
        <h2 class="text-center text-white">NOW SHOWING MOVIES</h2>
        <div class="row">
            {% for movie in now_showing_movies %}
                <div class="col-md-4 mb-4">
                    <div class="card" style="height: 100%;">
                        <div class="card-body d-flex flex-column">
                            <img class="card-img-top movie-image" src="{{ movie.image }}" alt="{{ movie.name }}">
                            <h5 class="card-title"><a class="white">{{ movie.name }}</a></h5>
                            <p class="card-text">Date: {{ movie.date }}</p>
                            <p class="card-text">Show Time: {{ movie.showtime }}</p>
                            <a href="{% url 'main:transaction' %}" class="btn btn-primary mt-auto">Book Now</a>
                            <!-- Add more details below the buttons as needed -->
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 and not forloop.last %}
                    </div><div class="row">
                {% endif %}
            {% endfor %}
        </div>
    </section>



   <!-- Upcoming Movies -->
   <section class="screening container mt-5">
    <h2 class="text-center text-white">UP COMING MOVIES</h2>
    <div class="row">
        {% for movie in upcoming_movies %}
            <div class="col-md-4 mb-4">
                <div class="card" style="height: 100%;">
                    <div class="card-body d-flex flex-column">
                        <img class="card-img-top movie-image" src="{{ movie.image }}" alt="{{ movie.name }}">
                        <h5 class="card-title"><a class="white">{{ movie.name }}</a></h5>
                        <p class="card-text">Date: {{ movie.date }}</p>
                        <a href="{% url 'main:transaction' %}" class="btn btn-primary mt-auto">Book Now</a>
                        <!-- Add more details below the buttons as needed -->
                    </div>
                </div>
            </div>
            {% if forloop.counter|divisibleby:3 and not forloop.last %}
                </div><div class="row">
            {% endif %}
        {% endfor %}
    </div>
</section>
<footer class="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <h6>About</h6>
                <p class="text-justify">"Discover the magic of movies with Filmax Cinemas – your go-to destination for an extraordinary cinematic experience. Streamlining convenience and excellence, our cutting-edge app puts showtimes, seat selection, and ticket booking in the palm of your hand. Join us in redefining movie-watching, where innovation meets comfort. Welcome to Filmax Cinemas – where movies come to life!"</p>
            </div>

            <div class="col-md-3">
                <h6>Quick Links</h6>
                <ul class="footer-links">
                    <li><a href="{% url 'main:about_us' %}">About Us</a></li>
                    <li><a href="{% url 'main:contact_us' %}">Contact Us</a></li>
                </ul>
            </div>

            <div class="col-md-3">
                <h6>Subscribe for Latest Updates</h6>
                <form action="#" method="post" class="input-group">
                    <input type="email" class="form-control" placeholder="Enter your email">
                    <button class="btn btn-secondary" type="submit">Subscribe</button>
                </form>
            </div>
        </div>
        <hr>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-6 col-xs-12">
                <p class="copyright-text">Copyright &copy; 2023 All Rights Reserved by
                    <a href="#" target="_blank">FILMAX CINEMAS</a>.
                </p>
            </div>
        </div>
    </div>
</footer>
</body>

</html>